name: Environment Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  environment-test:

    name: Environment Test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10, 12, 14, 16]

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup nodejs
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Installling dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint
      
      - name: Build
        run: yarn  run build

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1